HOST			= 

AR				= $(HOST)ar
CC				= $(HOST)gcc
CXX				= $(HOST)g++
RANLIB		= $(HOST)ranlib
JAVA			= $(HOST)javac

STRIP			= $(HOST)strip

DOXYGEN		= doxygen

INCDIR		= include
LIBDIR		= lib
SRCDIR 		= src
BINDIR 		= bin
OBJDIR		= obj
TESTDIR		= tests
DOCDIR		= doc

PREFIX		= /usr/local

CCFLAGS		+= \
						-g -ggdb \
						-Wall -rdynamic -fpic -funroll-loops -O2 \

ARFLAGS		+= \
						-rc \

CCFLAGS		+= \
						$(DEFINES) \
						-I$(INCDIR) \

ECHO			= echo -e

OK 				= \033[30;32mOK\033[m

