HOST			= 

AR				= $(HOST)ar
CC				= $(HOST)gcc
CXX				= $(HOST)g++
RANLIB		= $(HOST)ranlib
JAVA			= $(HOST)javac

STRIP			= $(HOST)strip

DOXYGEN		= doxygen

INCDIR		= include
LIBDIR		= lib
SRCDIR 		= src
BINDIR 		= bin
OBJDIR		= obj
TESTDIR		= tests
DOCDIR		= doc

PREFIX		= /usr/local

CCFLAGS		+= \
						-Wall -g -ggdb -rdynamic -fpic -funroll-loops -O2 $(DEFINES) \
						-I$(INCDIR) \
						-I$(SRCDIR)/$(INCDIR) \

ARFLAGS		= \
						rc \

ECHO			= echo -e

OK 				= \033[30;32mOK\033[m

